/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface IdliTextarea {
    /**
    * If true, the user cannot interact with the button. Defaults to `false`.
    */
    'disabled': boolean;
    /**
    * If true, the form will be in inline format. Defaults to `false`.
    */
    'inline': boolean;
    /**
    * The input field label.
    */
    'label': string;
    /**
    * The input field placeholder.
    */
    'placeholder': string;
    /**
    * The button size. Possible values are: `"sm"`, `"md"`, `"lg"`. Defaults to `"md"`.
    */
    'size': 'sm' | 'md' | 'lg';
    /**
    * Button variants Possible values are `"text"`. Defaults to `"text"`.
    */
    'type': 'text' | 'number';
    /**
    * The input field value.
    */
    'value': string;
    /**
    * Button variants Possible values are `"default"`, `"dashed"`. Defaults to `"default"`.
    */
    'variant': 'default' | 'dashed';
  }
}

declare global {


  interface HTMLIdliTextareaElement extends Components.IdliTextarea, HTMLStencilElement {}
  var HTMLIdliTextareaElement: {
    prototype: HTMLIdliTextareaElement;
    new (): HTMLIdliTextareaElement;
  };
  interface HTMLElementTagNameMap {
    'idli-textarea': HTMLIdliTextareaElement;
  }
}

declare namespace LocalJSX {
  interface IdliTextarea {
    /**
    * If true, the user cannot interact with the button. Defaults to `false`.
    */
    'disabled'?: boolean;
    /**
    * If true, the form will be in inline format. Defaults to `false`.
    */
    'inline'?: boolean;
    /**
    * The input field label.
    */
    'label'?: string;
    /**
    * On change of input a CustomEvent 'inputChange' will be triggered. Event details contains parent event, oldValue, newValue of input.
    */
    'onInputChange'?: (event: CustomEvent<any>) => void;
    /**
    * The input field placeholder.
    */
    'placeholder'?: string;
    /**
    * The button size. Possible values are: `"sm"`, `"md"`, `"lg"`. Defaults to `"md"`.
    */
    'size'?: 'sm' | 'md' | 'lg';
    /**
    * Button variants Possible values are `"text"`. Defaults to `"text"`.
    */
    'type'?: 'text' | 'number';
    /**
    * The input field value.
    */
    'value'?: string;
    /**
    * Button variants Possible values are `"default"`, `"dashed"`. Defaults to `"default"`.
    */
    'variant'?: 'default' | 'dashed';
  }

  interface IntrinsicElements {
    'idli-textarea': IdliTextarea;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'idli-textarea': LocalJSX.IdliTextarea & JSXBase.HTMLAttributes<HTMLIdliTextareaElement>;
    }
  }
}


